### ISSUE TITLE
Where can I find the Kuramoto-model dataset?

### ISSUE THREAD

**Issue by syyunn** [bnusss/GGN#1]
train_fp = './data/kuramoto/ERtrain-5000sample-1.1kc10node-100timestep-2vec.npy'
    val_fp = './data/kuramoto/ERval-1000sample-1.1kc10node-100timestep-2vec.npy'
    test_fp = './data/kuramoto/ERtest-1000sample-1.1kc10node-100timestep-2vec.npy'
    adj_fp = './data/kuramoto/ERadj-10sample-1.1kc10node-100timestep-2vec.npy'

Those file paths doesn't exist in the repo. Where can I get them?

**Comment by 3riccc** [comment]
Hi Yoon,

Thanks for getting in touch! Apologies for not publishing the code to
reproduce the Kuramoto experiments. We were using an external code base for
generating this dataset and didn't want to get into any licensing issues.

I am attaching the code that we used to generate the dataset in this email.
You should be able to reproduce our dataset generation by just running
`python generate_dataset.py`. Please let me know if you are able to
reproduce our results. I can look into it further if there are any issues.

Thanks,
ZhangZhang

Zachary Yoon <notifications@github.com> 于2020年1月10日周五 下午2:42写道：

**Comment by syyunn** [comment]
Thanks for the real-fast reply! I had just checked my email inbox of "syyun@snu.ac.kr" but can not find any file attached. Could you send me the code directly to me via this email if possible?

**Comment by syyunn** [comment]
Closed the issue after kindly getting the code for the random generation of the Kuramoto-model

**Comment by Macklemoreh** [comment]
Hi, I really appreciate this work. Could you share with me the data generation code on Kuramoto-model? Thank you!
